name: Bug report
description: Something isn't working
labels: bug
body:
  - type: textarea
    id: describe
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
